[package]
name = "chord-pairs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
egui = "0.23.0"
fon = "0.6.0"
num-integer = "0.1.45"
rand = "0.8.5"
rodio = "0.17.1"
twang = "0.9.0"
